name:                nai-auth
version:             0.1.0.0
github:              "narrativai/auth-sec-service"
license:             BSD3
author:              "Alex Springer"
maintainer:          "alex@narrativai.com"
copyright:           "2023 Alex Springer"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/narrativai/auth-sec-service#readme>

dependencies:
- base >= 4.7 && < 5
- bcrypt
- jwt
- yesod
- yesod-auth
- sqlite-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  nai-auth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nai-auth

tests:
  nai-auth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nai-auth
